table dim_geo
	lineageTag: 789e2cdf-85e3-4ac9-997a-a39f1a82188d

	column provincia
		dataType: string
		lineageTag: 2216207b-0938-4e8e-a579-c876690c4fe4
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: provincia

		annotation SummarizationSetBy = Automatic

	column provincia_id
		dataType: int64
		formatString: 0
		lineageTag: 3aa27d67-d3c3-458d-bac3-848aa508ab71
		summarizeBy: none
		sourceColumn: provincia_id

		annotation SummarizationSetBy = Automatic

	column departamento
		dataType: string
		lineageTag: 48905c0c-25ea-4dd9-8810-1c57342ff97e
		summarizeBy: none
		sourceColumn: departamento

		annotation SummarizationSetBy = Automatic

	column departamento_id
		dataType: int64
		formatString: 0
		lineageTag: 935fda9d-1165-423e-989b-9a17300d5ef0
		summarizeBy: none
		sourceColumn: departamento_id

		annotation SummarizationSetBy = Automatic

	column pais
		dataType: string
		lineageTag: 848bc1af-f757-4912-b0fe-2be31abecc39
		dataCategory: County
		summarizeBy: none
		sourceColumn: pais

		annotation SummarizationSetBy = Automatic

	hierarchy 'provincia Hierarchy'
		lineageTag: 3b60d8b7-c78b-4cdc-bb87-afcb7557083c

		level pais
			lineageTag: 7eeb3441-cac0-43ee-8253-6af78480f601
			column: pais

		level provincia
			lineageTag: 84af1ea9-c987-4a72-afaf-e5ffa73251ea
			column: provincia

		level departamento
			lineageTag: 35914204-b325-4d32-9959-b5d24aa36b7a
			column: departamento

	partition dim_geo = m
		mode: import
		source =
				let
				    Source = raw_mani_data,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"provincia", "provincia_id", "departamento", "departamento_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"departamento_id", Int64.Type}, {"provincia_id", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "departamento_fix", each if [departamento] = "" then "otros departamentos" else [departamento]),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "departamento_id_fix", each if [departamento_id] = null then ( ( [provincia_id] * 1000 ) + 999 ) else [departamento_id]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column1",{"departamento", "departamento_id"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"departamento_fix", "departamento"}, {"departamento_id_fix", "departamento_id"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"departamento_id", Int64.Type}}),
				    #"Removed Duplicates1" = Table.Distinct(#"Changed Type1", {"departamento_id"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates1", "pais", each "Argentina", type text)
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

