table fact_ProducerPrice
	lineageTag: 68ac77da-ac2e-4e93-8cb7-4c1b802c6f0d

	column observation_date
		dataType: string
		lineageTag: c1254391-7b8e-4221-9165-2cb6b9702ef8
		summarizeBy: none
		sourceColumn: observation_date

		annotation SummarizationSetBy = Automatic

	column producer_price
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8d1d3487-a83f-4b43-8121-edc8cbdf17c6
		summarizeBy: sum
		sourceColumn: producer_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column peanut_type
		dataType: string
		lineageTag: a29a6ade-3f12-4ce9-8712-8d671c1140ed
		summarizeBy: none
		sourceColumn: peanut_type

		annotation SummarizationSetBy = Automatic

	partition fact_ProducerPrice = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=WPU01830111&scale=left&cosd=1947-01-01&coed=2026-06-01&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-07-22&revision_date=2026-07-22&nd=1947-01-01"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"observation_date", type date}, {"WPU01830111", Currency.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"WPU01830111", "producer_price"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "peanut_type", each "Peanuts", type text),
				    #"Appended Query" = Table.Combine({#"Added Custom", priceIndex_pistachios, priceIndex_almonds, priceIndex_pecans, priceIndex_treeNuts, priceIndex_macadamia, priceIndex_filberts, priceIndex_walnut})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

