table dim_carriers
	lineageTag: 03ae7869-2171-4d25-ae84-a3a782c1b08a

	column rpcarrier
		dataType: string
		lineageTag: a6b8853d-7f07-4979-8890-010b5da14aa3
		summarizeBy: none
		sourceColumn: rpcarrier

		annotation SummarizationSetBy = Automatic

	column carrier_name
		dataType: string
		lineageTag: d843d813-1c39-4f24-81a2-f96204536684
		summarizeBy: none
		sourceColumn: carrier_name

		annotation SummarizationSetBy = Automatic

	partition dim_carriers = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lVhLd+K4Ev4rur26c06SzqSTdFgaAglgwGBenZlZKEYB3RiLkeXQzK+feshgIL24i3BOVKVHVX31VZX/+ONLEHy5+BKsldWJzESgbaozlYt2llyJSwHSvy5AaYhKqVnJc40ha8SkIfP3T1RiUqm3QKVlVZasxKtSIIAVFDQGIGiYzMGmzMkUDxBh9QTQQMXHEBQfVerkuQrIUKWFl4zNVllS8cIWX/SMtj7LrdT6E1uf2dbn6OAQMVO5O1eMSLGLil291bDulM2k0yaD11+KrleYoV3SZvrjM6NAjFr9LmjFG221q+hcClgnMR7SN9attp+9pc+HDDFAI5WZqtVDDs1oigbBckNmciGFNcVSiTACDRChxriOTpu0D6fXVbrUxVr0r6ZXYvH19asUHeWktm/pDvbBBtqHbxtbmeViZmy6wP1buctFGDZQi982fsH7x8HhdD4Ql0DphZQmGJpJpp1anHtqwpGZIMYm8f6WUsrwmvXRj6Y4dVTDoBJIUWmOMRs3e6KJIdtYneNzXqUQwYdKzWHXpZhzEH/MybOb4jXVSSkHMayj+GXmnTvTeWKyXGfVm+0GNF/YDSME7yR1FrXB9YzXuw5iRL0WZeC8c2gpkol+41thB6iSF27wnFa8N/+GljvfYXkq0+J/6hwlICSdNuh05EIBFOzSnOEW5IRb9GTPWPAOXY12GEtqCFv25POQcsmuTbbbRwRygzHXiE9SuqcTa+BFWmI6c8SG6NpnY/U/JvM2DtmrNXxB0A/En8X19c296ESi+XNjVc7hDN0CrarxS1o14hW8jLP+yHSQolLvCR+0kuuN3l8GayhqIv00Tb7felHubTLttEKOMSJ9b+qxU1oczeEjaD6B2uIUpCAhkJa5+GRVYviiCx/ymc6WuX/ajBOzf4eYfpdLOIoksbIfOkH8gYg0OhT2bFlIuzhnB4bMaMK31q1eLBXHfq8a6jVlHUBywm9EJCHxATaqECwTY8ZgmqHbmzJ3W52d3zxjtzfRXh+6ThWYyBBstlzJ/6Cv2eIBQjQCdaeBpA64GjA0x9+IcXTu5HmoQUgZi3f2VH5eiH7wHQEaOO6JQFmDcpmL+CoAnoO8IL4DPgiARMy6TBSoYd5oxEo8GwyivaGMkQESSyvdQQxF3UhXigfMIlFAYsA6EHDDgNe4IpQ+jZjh4h4eX2RbYtPj9KxogxqRWccb+iqPiIuDHtXIk0cVIfLJgLnbzD7MrswEzto+Oqb/yYV9tv6FeoUkgWBCKRDPJl0QZoHj/Pt/8PvBxCJzdndK+b3+kRk/2HUzwohKCqc/VFVhwMxZv0faUq6eFlVIwDJKn26p80jVEoq68wbBIsrCBmWH1UsRmiWgBmt6/BXrDojo8mf0UhycYQUE5EVkogjzvtIi7QmAfMosFMz3tTB20qm8akjAtDZCehjt4JBfhnbEPNF64F5JLcz61InPTIbIOg+k/Pv9L2z4nT30iDa2s4XaKPjJEuWd9Mgm9jGqffRJn6PYpMzGerg5HBmHmKSMn8kdFeJAfLu+vq6+fsKkFBNtrQrnUlU6bu+vmHWeEGtP5hek4DuBkvQhoIzAAeXf++7TvmzAqTiafVKxybcMp3nzF5zkjwE5lTDqA1OogSeEGV9FyBZQxji34zm/6bX4pITEHPkQQRrusp/QZ2guGmzoed0CaDJ4p3juVNul3qMPhFNfIckICKf8MEetbo1fXwupAKdLWVa7Gpeo8Nv/8xJm1FHExbNwsvi7OOfVETtihmrtPPXlT3CnjRzJ8m/Ebjr94Et8Gn9jMmvc0YPX68IpagARC68Im/0SeJyxE40R8FotoPlw1feCgPgNPVeH7PlHHax8gr53Ix7rgRBeBLzHzrwZHD/8UGVvGFK32CDXobfUfxdl9txyD3yLaJtJ+wrpssVlBtkdFqGxdCZbFO9iULg37SDlD+WWnQ5ZZh0XfT884Rsqq2X9uePSdU8z1GAugvaoMQpa4wvfa9/zhPM9LhkGN799fcc+2ybAe4K4CVoWV/Ys37kLe0Ak1QFeULkqOHpgHD2gHTMg0JU7cc0Dv6iG48sz3Jj5btFr+AygEMpN6bQaDzW1edmrY49RYsHn5AVt6pn3IlXpUT2ocbiCxvFAA/zKZB60GEMbucy0ElDJeOxqgen05oC9FCAQsfqv1U+dUHlnEAbUdz5Og36j+Yg+Lt0beJLH+tbSWYblb4CTUMA1rB4Q4rTT+WpvT5QmWKaYVFu3Jcu2OL2fpr5XdAeMAs+xV9uoHSfG+ZnQJ0MFowdqbPN5bcRo+xUCWZ2OB28i3kiNR7cZsB1MtK4EnyKvlDcfqNfjMFZyA5eR3zucdh3sN8ZBD49eQdMEHqTeKaC3hdLJSq2qW5lrGiq4Hemgazvcz/fE4UuBGJvClnx59AISImhhMIZjOALdG6rH76kx76hxcZiZvvLlb648wK/+APooaaQK4C4PTl0kxClMKYVVeB/UvYo3xhIILzuBfpdpsYuZ0zXghKzi8cqA0uUc6uLs0VU7zH21n6jIaY8q82wIa1mmknLI4tGkiyzeTddiZHbQJzwWLllVE6LrOR3RFwYYmr2Q6W4fm+yI1hmSIaVLq1cdO4FQIR6nLccARl4slWVNhyM4k0JsLcLiza0gTlI8Kbs+uYp7jJASfqvz/NetT8jZ3bsrE6XnR5wmfQJRWxjalyX+j8ecpv+U8uKJAZVflCRlEPMnhgF9oipyZ/XxGwd+HMWLb68vezot6WrILxiio4aQqTI/fOLgEA/ZD6MONwvy8r/jlfrNx6tj7EJmeBvUSD+KTflLjeJO10O1pBmUUkuBKI9xxulJfC3fu+8pGLhxnzinyHOVVrpN+mQDSpwv4w73zgLKt63iv5yZ+FlTapS1PA18DFtSXxl8vZ4y107jSnfiwNOOm61Si306v/URaf5MIM0h5uXHoTmz1nwf7Tn7eo6QR7w2k0IuDEZh7lGOVToyaf4O3A65hr/GZTqhUh5ypQ4jvz1StjhCF/cgA4JIjj497x8ZJ2P6RhREl/BHbo+gaBZL+kIy5lNuMPPjtXmHpK770dwfcsM5H+A9bZjywKf7ymuIMg13kNSKtMeB/w9KCV8f0/dAmDRgtpIfR1CNdzmFForoX/8C", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [rpcarrier = _t, carrier_name = _t])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

