table GatewaysNonstop
	lineageTag: 0075e436-1669-4e15-a894-7600572ac8a7

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 8195154f-f44d-4ba5-a649-3c1408aa4c17
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 26b717e6-5cb1-49e1-8174-595c4df95255
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 6092cfc0-cfe5-4a35-97e9-5e0acd11f882
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column airport_state
		dataType: string
		lineageTag: 6b62c6f9-76a1-485e-afec-fd68028bfaba
		summarizeBy: none
		sourceColumn: airport_state

		annotation SummarizationSetBy = Automatic

	partition GatewaysNonstop = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://data.bts.gov", [RelativePath = "/api/v3/views/hpjf-p2n3/query.csv"]),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Column8", "Column7", "Column6", "Column5"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Other Columns", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"change_2022_2023"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"gateway_airport"}, "Date", "Value"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Unpivoted Other Columns",{{"Value", Int64.Type}}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Changed Type", {{"Date", each Text.AfterDelimiter(_, "_"), type text}}),
				    #"Added Prefix" = Table.TransformColumns(#"Extracted Text After Delimiter", {{"Date", each _ & "-01-01", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Prefix",{{"Date", type date}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type1", "gateway_airport", Splitter.SplitTextByDelimiter(", ", QuoteStyle.Csv), {"city", "airport_state"}),
				    #"Filtered Rows" = Table.SelectRows(#"Split Column by Delimiter", each ([city] <> "Top 20" and [city] <> "Total"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

