table query
	lineageTag: 0075e436-1669-4e15-a894-7600572ac8a7

	column gateway_airport
		dataType: string
		lineageTag: df612f16-d9d5-45af-9a47-64a3bc924b42
		summarizeBy: none
		sourceColumn: gateway_airport

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 50ae677b-ba9b-431f-8044-fdfbe7d32adc
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 8195154f-f44d-4ba5-a649-3c1408aa4c17
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition query = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://data.bts.gov/api/v3/views/hpjf-p2n3/query.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Column8", "Column7", "Column6", "Column5"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Other Columns", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"change_2022_2023"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"gateway_airport"}, "Attribute", "Value")
				in
				    #"Unpivoted Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

