table SalesSupermarket
	lineageTag: 8637835c-9834-4ef6-83e5-794b390268e2

	column indice_tiempo
		dataType: dateTime
		formatString: Long Date
		lineageTag: 55832e0c-585d-4e06-a937-9954dfda1d26
		summarizeBy: none
		sourceColumn: indice_tiempo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a29c1697-52da-4702-b330-730299caa71f
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Category
		dataType: string
		lineageTag: 952d058f-00e4-4018-8bec-cc2f8ce9fc3b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition SalesSupermarket = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://infra.datos.gob.ar/catalog/sspm/dataset/455/distribution/455.1/download/ventas-totales-supermercados-2.csv"),[Delimiter=",", Columns=27, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"indice_tiempo", type date}, {"ventas_precios_corrientes", Currency.Type}, {"ventas_precios_constantes", Currency.Type}, {"ventas_precios_constantes_original", Currency.Type}, {"ventas_precios_constantes_desestacionalizada", Currency.Type}, {"ventas_precios_constantes_tendencia_ciclo", Currency.Type}, {"ventas_totales_canal_venta", Currency.Type}, {"salon_ventas", Currency.Type}, {"canales_on_line", Currency.Type}, {"ventas_totales_medio_pago", Currency.Type}, {"efectivo", Currency.Type}, {"tarjetas_debito", Currency.Type}, {"tarjetas_credito", Currency.Type}, {"otros_medios", Currency.Type}, {"ventas_totales_grupo_articulos", Currency.Type}, {"subtotal_ventas_alimentos_bebidas", Currency.Type}, {"bebidas", Currency.Type}, {"almacen", Currency.Type}, {"panaderia", Currency.Type}, {"lacteos", Currency.Type}, {"carnes", Currency.Type}, {"verduleria_fruteria", Currency.Type}, {"alimentos_preparados_rotiseria", Currency.Type}, {"articulos_limpieza_perfumeria", Currency.Type}, {"indumentaria_calzado_textiles_hogar", Currency.Type}, {"electronicos_articulos_hogar", Currency.Type}, {"otros", Currency.Type}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"indice_tiempo"}, "Attribute", "Value"),
				    #"Inserted Replaced Text" = Table.AddColumn(#"Unpivoted Other Columns", "Category", each Text.Replace(Text.Proper([Attribute]), "_", " "), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Replaced Text",{"Attribute"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

