table ShopHealthyStoresNYC
	lineageTag: d8b95239-83d4-41ba-bba2-f83d15f3a450

	column 'Store Name'
		dataType: string
		lineageTag: 5658d82a-59f8-41c0-9758-42c9f96d22e8
		summarizeBy: none
		sourceColumn: Store Name

		annotation SummarizationSetBy = Automatic

	column 'Year Awarded'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 20f477ab-5f85-42c6-92b8-2ae344308950
		summarizeBy: none
		sourceColumn: Year Awarded

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Program Wave'
		dataType: int64
		formatString: 0
		lineageTag: d294e15f-fdc4-40ab-b0c9-c498b9f2b2a7
		summarizeBy: sum
		sourceColumn: Program Wave

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: int64
		formatString: 0
		lineageTag: e3804d88-c2fe-49a8-a80a-9905bf300e64
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	partition ShopHealthyStoresNYC = m
		mode: import
		queryGroup: ShopsNYC
		source =
				let
				    Source = Csv.Document(Web.Contents("https://data.cityofnewyork.us", [RelativePath="/api/v3/views/ud4g-9x9z/export.csv?accessType=DOWNLOAD"]),[Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Added Suffix" = Table.TransformColumns(#"Promoted Headers", {{"Year Awarded", each _ & "-01-01", type text}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Suffix",{{"Year Awarded", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Store Name", "Street Address"}, dim_NYCLocation, {"Store Name", "Street Address"}, "dim_NYCLocation", JoinKind.LeftOuter),
				    #"Expanded dim_NYCLocation" = Table.ExpandTableColumn(#"Merged Queries", "dim_NYCLocation", {"LocationId"}, {"LocationId"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded dim_NYCLocation",{"Street Address", "Borough", "Zip #(lf)Code", "Latitude", "Longitude", "Community Board", "Council District", "Neighborhood Tabulation Area (NTA) (2020)", "BIN", "BBL", "Census Tract (2020)"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Program #(lf)Wave", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

