table Dax_Measures
	lineageTag: 62bf6d53-8831-415c-8d14-76b2595a7c5e

	measure '01 Asientos' = SUM( magnitud_rutas[asientos] )
		formatString: #,0
		lineageTag: 51e487b5-56dd-4101-9d91-083e73ce9131

	measure '02 Pasajeros' = SUM( magnitud_rutas[pasajeros] )
		formatString: #,0
		lineageTag: e8b9e0f1-611f-4986-8f68-a8e101647e15

	measure '03 Vuelos' = SUM( magnitud_rutas[vuelos] )
		formatString: #,0
		lineageTag: a19e3010-254b-4752-b019-9e77ce6066e7

	measure '04 D Count Destinos' = ```
			DISTINCTCOUNT( magnitud_rutas[destino] ) 
			```
		formatString: #,0
		lineageTag: dc6afbe5-2792-4d13-9551-78131d8ff224

	measure '05 D Count Origen' = DISTINCTCOUNT( magnitud_rutas[origen] )
		formatString: #,0
		lineageTag: 04c1ac83-2e20-4c93-9273-d4767b93b6b4

	measure '06 D Count Rutas' = DISTINCTCOUNT( magnitud_rutas[ruta_nombre] )
		formatString: #,0
		lineageTag: 3f003248-37ad-4c28-a65a-9545796d4bc7

	partition Dax_Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

