table dim_date
	lineageTag: e90ad77a-5b04-412d-bfd8-509b97440a63
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: e0200552-d726-4304-b009-72662871a5d5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 18deb472-41d5-4b6a-a4e2-2920679a61aa
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Start of Year'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6138147f-7706-4761-b867-266fde97904d
		summarizeBy: none
		sourceColumn: Start of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 48cd78ab-4658-4692-86e9-ccf56933efbd
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: d0753e29-e2da-46f5-b1f3-536db61f8a0a
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 737d529b-2ef0-43bb-bbad-8339ba80d6ba
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: db1388b8-9259-4a1b-b349-7713622d295e
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    MinDate = #date( Date.Year( List.Min( magnitud_rutas[indice_tiempo] ) ), 01, 01 ),
				    MaxDate = #date( Date.Year( List.Max( magnitud_rutas[indice_tiempo] ) ), 01, 01 ),
				    DiffDays = Duration.Days( MaxDate - MinDate ) + 1,
				    Dates = List.Dates( MinDate, DiffDays, #duration( 1, 0, 0, 0) ),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Year", "Start of Year", each Date.StartOfYear([Date]), type date),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Start of Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Month Name", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text)
				in
				    #"Inserted Day Name"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

