name: Fabric CICD - Prod Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Deploy to PROD - Use MAIN"
        required: true

# Requires permissions
permissions:
  # contents: read   # validate branch name
  contents: write  # Read and Write allowe - For branch name validation and branch deletion after the deploy to Prod

env:
  TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
  APP_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  APP_SECRET_KEY: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Call Fabric Notebook
        env:
          BRANCH_NAME: ${{ github.event.inputs.branch_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ci/scripts/run_nb_git_prod_deploy.py
