
name: Fabric CICD

on:
  pull_request:
    branches:
      - main
    types:
      - closed # start the action when the pull request to main is closed


  workflow_dispatch:   # Manual deploy to PROD
    inputs:
      target:
        description: "Target pipeline"
        required: true
        type: choice
        options:
          - finance
          - sales
          - operations

      deployToProd:
        description: "Deploy to PROD?"
        required: true
        type: choice
        options:
          - no
          - yes

env:
  TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
  APP_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  APP_SECRET_KEY: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
  GIT_CONNECTION_ID: ${{ vars.GIT_CONNECTION_ID }}
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  PR_TITLE: ${{ github.event.pull_request.title }}

  SALES_PIPELINE_ID: ${{ vars.SALES_PIPELINE_ID }}
  SALES_WORKSPACE_ID: ${{ vars.SALES_WORKSPACE_ID }}
  SALES_DEV_STAGE_ID: ${{ vars.SALES_DEV_STAGE_ID }}
  SALES_TEST_STAGE_ID: ${{ vars.SALES_TEST_STAGE_ID }}

  FINANCE_PIPELINE_ID: ${{ vars.FINANCE_PIPELINE_ID }}
  FINANCE_WORKSPACE_ID: ${{ vars.FINANCE_WORKSPACE_ID }}
  FINANCE_DEV_STAGE_ID: ${{ vars.FINANCE_DEV_STAGE_ID }}
  FINANCE_TEST_STAGE_ID: ${{ vars.FINANCE_TEST_STAGE_ID }}

  OPERATIONS_PIPELINE_ID: ${{ vars.OPERATIONS_PIPELINE_ID }}
  OPERATIONS_WORKSPACE_ID: ${{ vars.OPERATIONS_WORKSPACE_ID }}
  OPERATIONS_DEV_STAGE_ID: ${{ vars.OPERATIONS_DEV_STAGE_ID }}
  OPERATIONS_TEST_STAGE_ID: ${{ vars.OPERATIONS_TEST_STAGE_ID }}


jobs:

  deploy_to_test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed folder
        run: |
          echo "Detecting changed folder..."

          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          echo "$CHANGED_FILES"

          TARGETS=""

          if echo "$CHANGED_FILES" | grep -q "^DataOps/"; then
            TARGETS="$TARGETS sales"
          fi

          if echo "$CHANGED_FILES" | grep -q "^ws-finance/"; then
            TARGETS="$TARGETS finance"
          fi

          if echo "$CHANGED_FILES" | grep -q "^ws-deploy-poc/"; then
            TARGETS="$TARGETS operations"
          fi

          # clean spaces
          TARGETS=$(echo "$TARGETS" | xargs)

          if [ -z "$TARGETS" ]; then
            echo "SKIPPING PIPELINE → No relevant changes"
            echo "SKIP_PIPELINE=true" >> $GITHUB_ENV
          else
            echo "Detected targets: $TARGETS"
            echo "TARGETS=$TARGETS" >> $GITHUB_ENV
          fi

      - name: Get Fabric token
        if: env.SKIP_PIPELINE != 'true'
        run: |
          TOKEN=$(curl -s -X POST https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=$APP_CLIENT_ID" \
          -d "client_secret=$APP_SECRET_KEY" \
          -d "grant_type=client_credentials" \
          -d "scope=https://api.fabric.microsoft.com/.default" \
          | jq -r .access_token)

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Set up Python
        if: env.SKIP_PIPELINE != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'ci/requirements/requirements.txt'

      - name: Install dependencies
        if: env.SKIP_PIPELINE != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r ci/requirements/requirements.txt

      - name: Deploy DEV → TEST
        if: env.SKIP_PIPELINE != 'true'
        run: |
          python ci/scripts/sync_workspace.py

      - name: Log deployment (SOX)
        if: env.SKIP_PIPELINE != 'true'
        run: |
          python ci/scripts/log_deployment_pipeline.py

      - name: Save deployment log in Fabric
        if: env.SKIP_PIPELINE != 'true'
        run: |
          python ci/scripts/save_log_fabric.py

  deploy_to_prod:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed folder
        run: |
          echo "Detecting changed folder..."

          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "^DataOps/"; then
            echo "TARGET=sales" >> $GITHUB_ENV

          elif echo "$CHANGED_FILES" | grep -q "^ws-finance/"; then
            echo "TARGET=finance" >> $GITHUB_ENV

          elif echo "$CHANGED_FILES" | grep -q "^ws-deploy-poc/"; then
            echo "TARGET=operations" >> $GITHUB_ENV

          else
            echo "No matching folder → defaulting to finance"
            echo "TARGET=finance" >> $GITHUB_ENV
          fi

      - name: Set pipeline configuration
        run: |
          if [ "${{ github.event.inputs.target }}" == "finance" ]; then
            echo "PIPELINE_ID=${{ vars.FINANCE_PIPELINE_ID }}" >> $GITHUB_ENV
            echo "DEV_STAGE_ID=${{ vars.FINANCE_DEV_STAGE_ID }}" >> $GITHUB_ENV
            echo "TEST_STAGE_ID=${{ vars.FINANCE_TEST_STAGE_ID }}" >> $GITHUB_ENV
            echo "PROD_STAGE_ID=${{ vars.FINANCE_PROD_STAGE_ID }}" >> $GITHUB_ENV

          elif [ "${{ github.event.inputs.target }}" == "sales" ]; then
            echo "PIPELINE_ID=${{ vars.SALES_PIPELINE_ID }}" >> $GITHUB_ENV
            echo "DEV_STAGE_ID=${{ vars.SALES_DEV_STAGE_ID }}" >> $GITHUB_ENV
            echo "TEST_STAGE_ID=${{ vars.SALES_TEST_STAGE_ID }}" >> $GITHUB_ENV
            echo "PROD_STAGE_ID=${{ vars.SALES_PROD_STAGE_ID }}" >> $GITHUB_ENV

          elif [ "${{ github.event.inputs.target }}" == "operations" ]; then
            echo "PIPELINE_ID=${{ vars.OPERATIONS_PIPELINE_ID }}" >> $GITHUB_ENV
            echo "DEV_STAGE_ID=${{ vars.OPERATIONS_DEV_STAGE_ID }}" >> $GITHUB_ENV
            echo "TEST_STAGE_ID=${{ vars.OPERATIONS_TEST_STAGE_ID }}" >> $GITHUB_ENV
            echo "PROD_STAGE_ID=${{ vars.OPERATIONS_PROD_STAGE_ID }}" >> $GITHUB_ENV
          fi

      - name: Get Fabric token
        run: |
          TOKEN=$(curl -s -X POST https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=$APP_CLIENT_ID" \
          -d "client_secret=$APP_SECRET_KEY" \
          -d "grant_type=client_credentials" \
          -d "scope=https://api.fabric.microsoft.com/.default" \
          | jq -r .access_token)

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'ci/requirements/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci/requirements/requirements.txt

      - name: Check status before deploy
        run: |
          response=$(curl -s -X GET https://api.fabric.microsoft.com/v1/workspaces/$WORKSPACE_ID/git/status \
            -H "Authorization: Bearer $TOKEN")

          echo "Raw response:"
          echo "$response"

          changes_count=$(echo "$response" | jq '.changes | length')

          if [ "$changes_count" -eq 0 ]; then
            echo "No changes detected"
          else
            echo "Changes detected:"

            echo "$response" | jq -r '
              .changes[] |
              [
                .itemMetadata.itemIdentifier.objectId,
                .itemMetadata.itemType,
                .itemMetadata.displayName,
                .workspaceChange,
                .remoteChange,
                .conflictType
              ] | @tsv
            ' | while IFS=$'\t' read -r objectId itemType displayName conflictType; do
              echo "--------------------------------------"
              echo "Object ID: $objectId"
              echo "Type: $itemType"
              echo "Name: $displayName"
              echo "Workspace Change Type: $workspaceChange"
              echo "Remote Change Type: $remoteChange"
              echo "Conflict: $conflictType"
            done
          fi

          echo "HAS_CHANGES=$changes_count" >> $GITHUB_ENV

      - name: Deploy TEST → PROD
        run: |
          echo "Starting deployment..."

          response=$(curl -i -s -X POST https://api.fabric.microsoft.com/v1/deploymentPipelines/$PIPELINE_ID/deploy \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
                  \"sourceStageId\": \"$TEST_STAGE_ID\",
                  \"targetStageId\": \"$PROD_STAGE_ID\"
                }")

          OPERATION_ID=$(echo "$response" \
            | grep -i "^deployment-id:" \
            | head -n 1 \
            | cut -d':' -f2 \
            | tr -d '\r[:space:]')

          echo "Captured OPERATION_ID: $OPERATION_ID"

          if [ -z "$OPERATION_ID" ]; then
            echo "No operationId returned → possible no changes or immediate deployment"
          else
            echo "Operation ID: $OPERATION_ID"
            echo "OPERATION_ID=$OPERATION_ID" >> $GITHUB_ENV
          fi

      - name: Deployment Summary
        run: |
          echo "### Test → Prod Deployment" >> $GITHUB_STEP_SUMMARY
          echo "- Pipeline: $PIPELINE_ID" >> $GITHUB_STEP_SUMMARY
          echo "- Operation: $OPERATION_ID" >> $GITHUB_STEP_SUMMARY

      - name: Log deployment (SOX - PROD)
        run: |
          python ci/scripts/log_deployment_pipeline.py
